### ISSUE TITLE
Error in AIX servers: "module_stderr": "Shared connection to x.x.x.x closed.\r\n"

### ISSUE THREAD

**Issue by edrendar** [IBM/ansible-power-aix#199]
**Symptom**
In some AIX machines when I run the module "ibm.power_aix.flrtvc" I got this error: **module_stderr": "Shared connection to x.x.x.x closed.\r\n**

I looked on google about this error, but I'm not able to get a successful result.

**Snip from the ansible controller**
```
[WARNING]: Ansible is being run in a world writable directory (/mnt/c/Users/105487781/Downloads/ansible), ignoring it as an ansible.cfg source. For more information see
https://docs.ansible.com/ansible/devel/reference_appendices/config.html#cfg-in-world-writable-dir
ansible-playbook [core 2.12.4]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/nifc/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/nifc/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True
Using /etc/ansible/ansible.cfg as config file
SSH password:
BECOME password[defaults to SSH password]:
Parsed 9.3.95.162, inventory source with host_list plugin
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.
PLAYBOOK: AIX_vulnerabilty_patching.yml ************************************************************************************************************************************************
1 plays in AIX_vulnerabilty_patching.yml
PLAY [Patching AIX Security Vulnerabilities] *******************************************************************************************************************************************
META: ran handlers
TASK [Downloading and Installing Vulnerabilities] **************************************************************************************************************************************
task path: /mnt/c/Users/105487781/Downloads/ansible/AIX_vulnerabilty_patching.yml:16
<9.3.95.162> ESTABLISH SSH CONNECTION FOR USER: None
<9.3.95.162> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o ConnectTimeout=10 -o 'ControlPath="/home/nifc/.ansible/cp/79e8cc6879"' 9.3.95.162 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<9.3.95.162> (0, b'/home/nifc\n', b'')
<9.3.95.162> ESTABLISH SSH CONNECTION FOR USER: None
<9.3.95.162> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o ConnectTimeout=10 -o 'ControlPath="/home/nifc/.ansible/cp/79e8cc6879"' 9.3.95.162 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/nifc/.ansible/tmp `"&& mkdir "` echo /home/nifc/.ansible/tmp/ansible-tmp-1651693208.5635352-122-50981442245670 `" && echo ansible-tmp-1651693208.5635352-122-50981442245670="` echo /home/nifc/.ansible/tmp/ansible-tmp-1651693208.5635352-122-50981442245670 `" ) && sleep 0'"'"''
<9.3.95.162> (0, b'ansible-tmp-1651693208.5635352-122-50981442245670=/home/nifc/.ansible/tmp/ansible-tmp-1651693208.5635352-122-50981442245670\n', b'')
<9.3.95.162> Attempting python interpreter discovery
<9.3.95.162> ESTABLISH SSH CONNECTION FOR USER: None
<9.3.95.162> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o ConnectTimeout=10 -o 'ControlPath="/home/nifc/.ansible/cp/79e8cc6879"' 9.3.95.162 '/bin/sh -c '"'"'echo PLATFORM; uname; echo FOUND; command -v '"'"'"'"'"'"'"'"'python3.10'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.9'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.8'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.7'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.6'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python3.5'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/bin/python3'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/libexec/platform-python'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python2.7'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python2.6'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'/usr/bin/python'"'"'"'"'"'"'"'"'; command -v '"'"'"'"'"'"'"'"'python'"'"'"'"'"'"'"'"'; echo ENDFOUND && sleep 0'"'"''
<9.3.95.162> (0, b'PLATFORM\nAIX\nFOUND\n/usr/bin/python2.7\n/usr/bin/python\n/usr/bin/python\nENDFOUND\n', b'')
<9.3.95.162> Python interpreter discovery fallback (unsupported platform for extended discovery: aix)
Using module file /home/nifc/.ansible/collections/ansible_collections/ibm/power_aix/plugins/modules/flrtvc.py
<9.3.95.162> PUT /home/nifc/.ansible/tmp/ansible-local-117kvwhdhbl/tmp3kx76u31 TO /home/nifc/.ansible/tmp/ansible-tmp-1651693208.5635352-122-50981442245670/AnsiballZ_flrtvc.py
<9.3.95.162> SSH: EXEC sshpass -d10 sftp -o BatchMode=no -b - -C -o ControlMaster=auto -o ControlPersist=60s -o ConnectTimeout=10 -o 'ControlPath="/home/nifc/.ansible/cp/79e8cc6879"' '[9.3.95.162]'
<9.3.95.162> (0, b'sftp> put /home/nifc/.ansible/tmp/ansible-local-117kvwhdhbl/tmp3kx76u31 /home/nifc/.ansible/tmp/ansible-tmp-1651693208.5635352-122-50981442245670/AnsiballZ_flrtvc.py\n', b'')
<9.3.95.162> ESTABLISH SSH CONNECTION FOR USER: None
<9.3.95.162> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o ConnectTimeout=10 -o 'ControlPath="/home/nifc/.ansible/cp/79e8cc6879"' 9.3.95.162 '/bin/sh -c '"'"'chmod u+x /home/nifc/.ansible/tmp/ansible-tmp-1651693208.5635352-122-50981442245670/ /home/nifc/.ansible/tmp/ansible-tmp-1651693208.5635352-122-50981442245670/AnsiballZ_flrtvc.py && sleep 0'"'"''
<9.3.95.162> (0, b'', b'')
<9.3.95.162> ESTABLISH SSH CONNECTION FOR USER: None
<9.3.95.162> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o ConnectTimeout=10 -o 'ControlPath="/home/nifc/.ansible/cp/79e8cc6879"' -tt 9.3.95.162 '/bin/sh -c '"'"'sudo -H -S -p "[sudo via ansible, key=dtbqwoncejhrdxfzxfzvqxhztkfhjmdh] password:" -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-dtbqwoncejhrdxfzxfzvqxhztkfhjmdh ; /usr/bin/python2.7 /home/nifc/.ansible/tmp/ansible-tmp-1651693208.5635352-122-50981442245670/AnsiballZ_flrtvc.py'"'"'"'"'"'"'"'"' && sleep 0'"'"''
Escalation succeeded
<9.3.95.162> (1, b'\r\nTraceback (most recent call last):\r\n  File "/home/nifc/.ansible/tmp/ansible-tmp-1651693208.5635352-122-50981442245670/AnsiballZ_flrtvc.py", line 107, in <module>\r\n    _ansiballz_main()\r\n  File "/home/nifc/.ansible/tmp/ansible-tmp-1651693208.5635352-122-50981442245670/AnsiballZ_flrtvc.py", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File "/home/nifc/.ansible/tmp/ansible-tmp-1651693208.5635352-122-50981442245670/AnsiballZ_flrtvc.py", line 48, in invoke_module\r\n    run_name=\'__main__\', alter_sys=True)\r\n  File "/opt/freeware/lib/python2.7/runpy.py", line 176, in run_module\r\n    fname, loader, pkg_name)\r\n  File "/opt/freeware/lib/python2.7/runpy.py", line 82, in _run_module_code\r\n    mod_name, mod_fname, mod_loader, pkg_name)\r\n  File "/opt/freeware/lib/python2.7/runpy.py", line 72, in _run_code\r\n    exec code in run_globals\r\n  File "/tmp/ansible_ibm.power_aix.flrtvc_payload_3Yjbf1/ansible_ibm.power_aix.flrtvc_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/flrtvc.py", line 1314, in <module>\r\n  File "/tmp/ansible_ibm.power_aix.flrtvc_payload_3Yjbf1/ansible_ibm.power_aix.flrtvc_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/flrtvc.py", line 1280, in main\r\n  File "/tmp/ansible_ibm.power_aix.flrtvc_payload_3Yjbf1/ansible_ibm.power_aix.flrtvc_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/flrtvc.py", line 975, in run_parser\r\nTypeError: expected string or buffer\r\n', b'Shared connection to 9.3.95.162 closed.\r\n')
<9.3.95.162> Failed to connect to the host via ssh: Shared connection to 9.3.95.162 closed.
<9.3.95.162> ESTABLISH SSH CONNECTION FOR USER: None
<9.3.95.162> SSH: EXEC sshpass -d10 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o ConnectTimeout=10 -o 'ControlPath="/home/nifc/.ansible/cp/79e8cc6879"' 9.3.95.162 '/bin/sh -c '"'"'rm -f -r /home/nifc/.ansible/tmp/ansible-tmp-1651693208.5635352-122-50981442245670/ > /dev/null 2>&1 && sleep 0'"'"''
<9.3.95.162> (0, b'', b'')
[WARNING]: Platform aix on host 9.3.95.162 is using the discovered Python interpreter at /usr/bin/python2.7, but future installation of another Python interpreter could change the
meaning of that path. See https://docs.ansible.com/ansible-core/2.12/reference_appendices/interpreter_discovery.html for more information.
fatal: [9.3.95.162]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python2.7"
    },
    "changed": false,
    "module_stderr": "Shared connection to 9.3.95.162 closed.\r\n",
    "module_stdout": "\r\nTraceback (most recent call last):\r\n  File \"/home/nifc/.ansible/tmp/ansible-tmp-1651693208.5635352-122-50981442245670/AnsiballZ_flrtvc.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/nifc/.ansible/tmp/ansible-tmp-1651693208.5635352-122-50981442245670/AnsiballZ_flrtvc.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/nifc/.ansible/tmp/ansible-tmp-1651693208.5635352-122-50981442245670/AnsiballZ_flrtvc.py\", line 48, in invoke_module\r\n    run_name='__main__', alter_sys=True)\r\n  File \"/opt/freeware/lib/python2.7/runpy.py\", line 176, in run_module\r\n    fname, loader, pkg_name)\r\n  File \"/opt/freeware/lib/python2.7/runpy.py\", line 82, in _run_module_code\r\n    mod_name, mod_fname, mod_loader, pkg_name)\r\n  File \"/opt/freeware/lib/python2.7/runpy.py\", line 72, in _run_code\r\n    exec code in run_globals\r\n  File \"/tmp/ansible_ibm.power_aix.flrtvc_payload_3Yjbf1/ansible_ibm.power_aix.flrtvc_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/flrtvc.py\", line 1314, in <module>\r\n  File \"/tmp/ansible_ibm.power_aix.flrtvc_payload_3Yjbf1/ansible_ibm.power_aix.flrtvc_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/flrtvc.py\", line 1280, in main\r\n  File \"/tmp/ansible_ibm.power_aix.flrtvc_payload_3Yjbf1/ansible_ibm.power_aix.flrtvc_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/flrtvc.py\", line 975, in run_parser\r\nTypeError: expected string or buffer\r\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
PLAY RECAP *****************************************************************************************************************************************************************************
9.3.95.162                 : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

OS: Red Hat Enterprise Linux Server 7.9
Python Version: 3.6.8
OpenSSH Version: 7.4p1
Ansible Version: 2.11.2
AIX Collection Version: ibm.power_aix 1.4.0

**Comment by GreenRodger8** [comment]
Hello,
What version of AIX was the end point with the error?
Also, could you provide the playbook that produced this error?
Thank you.

**Comment by nitismis** [comment]
Not able to recreate the issue.
