### ISSUE TITLE
flrtvc module failing trying to use a string on a bytes like object in run_download

### ISSUE THREAD

**Issue by christopher-horn** [IBM/ansible-power-aix#324]
**Describe the bug**
The flrtvc module fails trying to use a string on a bytes like object in run_download

**To Reproduce**
```
    - name: Install sec and hyper patches
      flrtvc:
        path: /tmp/flrtvc
        save_report: true
        extend_fs: true
        protocol: https
        force: false
        clean: false
        verbose: false
      environment:
        PATH: "/usr/bin:/usr/sbin/:/opt/freeware/bin"
      register: result
```

**Expected behavior**
Module runs as expected and downloads the flrtvc tool and executes it.

**Screenshots**
```
TASK [aix_postinstall : Install sec and hyper patches] *************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: cannot use a string pattern on a bytes-like object
fatal: [p1270-pvm1.p1270.cecc.ihost.com]: FAILED! => changed=false
module_stderr: |-
    Shared connection to 129.40.94.41 closed.
module_stdout: |-
    Traceback (most recent call last):
     File "/home/cecadmin/.ansible/tmp/ansible-tmp-1692107359.132368-93400-11590752473173/AnsiballZ_flrtvc.py", line 107, in
        _ansiballz_main()
     File "/home/cecadmin/.ansible/tmp/ansible-tmp-1692107359.132368-93400-11590752473173/AnsiballZ_flrtvc.py", line 99, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
     File "/home/cecadmin/.ansible/tmp/ansible-tmp-1692107359.132368-93400-11590752473173/AnsiballZ_flrtvc.py", line 47, in invoke_module
        runpy.run_module(mod_name='ansible_collections.ibm.power_aix.plugins.modules.flrtvc', init_globals=dict(_module_fqn='ansible_collections.ibm.power_aix.plugins.modules.flrtvc', _modlib_path=modlib_path),
     File "/usr/opt/python3/lib/python3.9/runpy.py", line 210, in run_module
        return _run_module_code(code, init_globals, run_name, mod_spec)
     File "/usr/opt/python3/lib/python3.9/runpy.py", line 97, in _run_module_code
        _run_code(code, mod_globals, init_globals,
     File "/usr/opt/python3/lib/python3.9/runpy.py", line 87, in _run_code
        exec(code, run_globals)
     File "/tmp/ansible_flrtvc_payload_dgukoa13/ansible_flrtvc_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/flrtvc.py", line 1320, in
     File "/tmp/ansible_flrtvc_payload_dgukoa13/ansible_flrtvc_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/flrtvc.py", line 1292, in main
     File "/tmp/ansible_flrtvc_payload_dgukoa13/ansible_flrtvc_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/flrtvc.py", line 1062, in run_downloader
     File "/usr/opt/python3/lib/python3.9/re.py", line 241, in findall
        return _compile(pattern, flags).findall(string)
    TypeError: cannot use a string pattern on a bytes-like object
msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
rc: 1
```

**Environment (please complete the following information):**
On target:
 - OS: 7300-01-02-2320
 - Python Version: 3.9.12
 - OpenSSH Version: 8.1.112.1201

On server:
 - Red Hat 8.8 ppc64le
 - Ansible Version: 2.14.2
 - Python Version: 3.11.2 
 - AIX Collection Version: 1.6.4

**Additional context**
Tested with and without running `dnf update` before calling flrtvc module

**Comment by nitismis** [comment]
Thanks for reporting the issue. We will look into this.

**Comment by nitismis** [comment]
PR is merged now.
