### ISSUE TITLE
Bad default value for parts attribute in installp.py

### ISSUE THREAD

**Issue by pbfinley1911** [IBM/ansible-power-aix#33]
**Describe the bug**
There's an issue with module installp.py   (Reported by dpkshetty)

Around line 282:  this will cause an error because of the default used with parts (None).

parts = module.params['parts']
    strparts = ''
    for part in parts:
        if part == 'root':
            strparts += 'r'
        elif part == 'share':
            strparts += 's'
        elif part == 'usr':
            strparts += 'u'

**To Reproduce**
  - name: Install package from repository
    ibm.power_aix.installp:
      action: apply
      bosboot: False
      device: /export/nim/lpp_source/723lpp_res
      install_list: tk
      agree_licenses: True

**Expected behavior**
The fileset should attempt to install without traceback errors

**Screenshots**
This will produce the following error if a value isn't passed in for the parts attribute:
Traceback (most recent call last):
  File "/.ansible/tmp/ansible-tmp-1598275717.76-6642173712374/AnsiballZ_installp.py", line 102, in <module>
    _ansiballz_main()
  File "/.ansible/tmp/ansible-tmp-1598275717.76-6642173712374/AnsiballZ_installp.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/.ansible/tmp/ansible-tmp-1598275717.76-6642173712374/AnsiballZ_installp.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.ibm.power_aix.plugins.modules.installp', init_globals=None, run_name='__main__', alter_sys=True)
  File "/opt/freeware/lib/python2.7/runpy.py", line 176, in run_module
    fname, loader, pkg_name)
  File "/opt/freeware/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/opt/freeware/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_ibm.power_aix.installp_payload_enXNvv/ansible_ibm.power_aix.installp_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/installp.py", line 344, in <module>
  File "/tmp/ansible_ibm.power_aix.installp_payload_enXNvv/ansible_ibm.power_aix.installp_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/installp.py", line 282, in main
TypeError: 'NoneType' object is not iterable

**Environment (please complete the following information):**
 - OS: AIX 7.2 TL4
 - Python Version 2.7.5

**Comment by dpkshetty** [comment]
Thanks @pbfinley1911 for opening the issue on my behalf, appreciate it 👍

**Comment by pbfinley1911** [comment]
@dpkshetty  You're welcome.  Let me know if you need the module patched before the team releases the change.  It's a minor change.

**Comment by robinvy** [comment]
Fixed in the Pull Request #35
