### ISSUE TITLE
Impossible to remove ifix

### ISSUE THREAD

**Issue by alexistrate87** [IBM/ansible-power-aix#383]
Hello,

I have been using the emgr module from ibm.power_aix collection to manage the interim fixes. The version of the collection is 1.7.2

I have inspected https://galaxy.ansible.com/ui/repo/published/ibm/power_aix/content/module/emgr/ for the way to remove an ifix and found it to be:

  - name: "UNINSTALL IFIX single 00F7CD554C00050615051822"
    ibm.power_aix.emgr:
      action: remove
      ifix_vuid: 00F7CD554C00050615051822

 - OS: 7200-05-04-2220
bash-5.1$ ansible --version
ansible [core 2.15.7rc1]
  config file = None
  configured module search path = ['/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.18 (main, Sep  7 2023, 00:00:00) [GCC 11.4.1 20230605 (Red Hat 11.4.1-2)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True

The error is:

TASK [vios_manage_ifix : UNINSTALL IFIX single 00F7CD554C00050615051822] *******
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'split'
fatal: [gva1249]: FAILED! => {"changed": false, "module_stderr": "Connection to gva1249 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1701364479.3631077-41-270609404218519/AnsiballZ_emgr.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1701364479.3631077-41-270609404218519/AnsiballZ_emgr.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1701364479.3631077-41-270609404218519/AnsiballZ_emgr.py\", line 48, in invoke_module\r\n    run_name='__main__', alter_sys=True)\r\n  File \"/opt/freeware/lib/python2.7/runpy.py\", line 188, in run_module\r\n    fname, loader, pkg_name)\r\n  File \"/opt/freeware/lib/python2.7/runpy.py…

What would be the proper task/play to uninstall an ifix.

**Comment by nitismis** [comment]
Hi @alexistrate87 
The playbook looks good. At first look it seems that module is trying to split on Nonetype object when expecting a string.
Can you run the playbook with -vvv option and send us the full output. Also, I see the python version detected is 3.9.18 but here it is 2.7: /opt/freeware/lib/python2.7/runpy.py, Not sure how it is happening or if it has any impact. But please copy the output of -vvv option and we will have a look.

**Comment by tolimar** [comment]
I think I'm facing the same issue.
The part of our playbook would be:
```
    - name: Remove installed ifixes for openssl.base - DEBUG
      ibm.power_aix.emgr:
        action: remove
        ifix_label: "{{ item }}"
      with_items:
        - "1022104a"

```

Running the playbook with -vvv shows the following:
```
TASK [Remove installed ifixes for openssl.base - DEBUG] **********************************************************************************************************************************
task path: xx/ansible/playbooks/aix-update-openssl.yml:33
Using module file /home/reichle/.ansible/collections/ansible_collections/ibm/power_aix/plugins/modules/emgr.py
Pipelining is enabled.
<XXXX> ESTABLISH SSH CONNECTION FOR USER: root
<XXXX> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o 'ControlPath="/home/reichle/.ansible/cp/6f3ce90560"' XXXX '/bin/sh -c '"'"'/opt/bin/python3 && sleep 0'"'"''
<XXXX> (1, b'', b'Traceback (most recent call last):\n  File "<stdin>", line 107, in <module>\n  File "<stdin>", line 99, in _ansiballz_main\n  File "<stdin>", line 48, in invoke_module\n  File "/opt/lib/python3.7/runpy.py", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File "/opt/lib/python3.7/runpy.py", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File "/opt/lib/python3.7/runpy.py", line 85, in _run_code\n    exec(code, run_globals)\n  File "/tmp/ansible_ibm.power_aix.emgr_payload_mdnbbxj1/ansible_ibm.power_aix.emgr_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/emgr.py", line 625, in <module>\n  File "/tmp/ansible_ibm.power_aix.emgr_payload_mdnbbxj1/ansible_ibm.power_aix.emgr_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/emgr.py", line 512, in main\n  File "/tmp/ansible_ibm.power_aix.emgr_payload_mdnbbxj1/ansible_ibm.power_aix.emgr_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/emgr.py", line 341, in is_ifix_installed\nAttributeError: \'NoneType\' object has no attribute \'split\'\n')
<XXXX> Failed to connect to the host via ssh: Traceback (most recent call last):
  File "<stdin>", line 107, in <module>
  File "<stdin>", line 99, in _ansiballz_main
  File "<stdin>", line 48, in invoke_module
  File "/opt/lib/python3.7/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/opt/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/opt/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_ibm.power_aix.emgr_payload_mdnbbxj1/ansible_ibm.power_aix.emgr_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/emgr.py", line 625, in <module>
  File "/tmp/ansible_ibm.power_aix.emgr_payload_mdnbbxj1/ansible_ibm.power_aix.emgr_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/emgr.py", line 512, in main
  File "/tmp/ansible_ibm.power_aix.emgr_payload_mdnbbxj1/ansible_ibm.power_aix.emgr_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/emgr.py", line 341, in is_ifix_installed
AttributeError: 'NoneType' object has no attribute 'split'
The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 107, in <module>
  File "<stdin>", line 99, in _ansiballz_main
  File "<stdin>", line 48, in invoke_module
  File "/opt/lib/python3.7/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/opt/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/opt/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_ibm.power_aix.emgr_payload_mdnbbxj1/ansible_ibm.power_aix.emgr_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/emgr.py", line 625, in <module>
  File "/tmp/ansible_ibm.power_aix.emgr_payload_mdnbbxj1/ansible_ibm.power_aix.emgr_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/emgr.py", line 512, in main
  File "/tmp/ansible_ibm.power_aix.emgr_payload_mdnbbxj1/ansible_ibm.power_aix.emgr_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/emgr.py", line 341, in is_ifix_installed
AttributeError: 'NoneType' object has no attribute 'split'
failed: [XXXX] (item=1022104a) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": "1022104a",
    "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 107, in <module>\n  File \"<stdin>\", line 99, in _ansiballz_main\n  File \"<stdin>\", line 48, in invoke_module\n  File \"/opt/lib/python3.7/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/opt/lib/python3.7/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/opt/lib/python3.7/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_ibm.power_aix.emgr_payload_mdnbbxj1/ansible_ibm.power_aix.emgr_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/emgr.py\", line 625, in <module>\n  File \"/tmp/ansible_ibm.power_aix.emgr_payload_mdnbbxj1/ansible_ibm.power_aix.emgr_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/emgr.py\", line 512, in main\n  File \"/tmp/ansible_ibm.power_aix.emgr_payload_mdnbbxj1/ansible_ibm.power_aix.emgr_payload.zip/ansible_collections/ibm/power_aix/plugins/modules/emgr.py\", line 341, in is_ifix_installed\nAttributeError: 'NoneType' object has no attribute 'split'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

```

ansible version:
```
$ ansible --version
ansible [core 2.14.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/reichle/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/reichle/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

Module version:
```
$ ansible-galaxy collection list ibm.power_aix

# /.ansible/collections/ansible_collections
Collection    Version
------------- -------
ibm.power_aix 1.7.2  

```

**Comment by tolimar** [comment]
FWIW:  Downgrading to 1.7.0 doesn't help, downgrading to 1.6.1 does.

**Comment by nitismis** [comment]
The fix is merged through this PR: https://github.com/IBM/ansible-power-aix/pull/384
Please replace emgr module in the collection: https://github.com/IBM/ansible-power-aix/blob/dev-collection/plugins/modules/emgr.py
Thanks

**Comment by alexistrate87** [comment]
Hello, 

Thank you for the fix. Our AWX instance is configured to automatically download the collection on job request. Hence this is overwriting the fixed emgr.py.

When is this going to be integrated in the newest ibm.power_aix collection ?

Thank you.

**Comment by nitismis** [comment]
You can expect a new collection release by early 1st week of Jan, 24

Thanks.
